# https://nookipedia.com/wiki/Fish
- id: "angelfish"
  name: "Angelfish"
  size: 10
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000011111100
  emoji: "ğŸ "
- id: "arowana"
  name: "Arowana"
  size: 70
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000011111000
- id: "barbel_steed"
  name: "Barbel Steed"
  size: 20
  rarity: 0
  location: "river"
  activeMonths: 0b001000000110
- id: "bass"
  name: "Bass"
  size: 40
  rarity: 0
  location: "river"
- id: "bitterling"
  name: "Bitterling"
  size: 8
  rarity: 0
  location: "river"
  activeMonths: 0b110000000011
  emoji: "ğŸ "
- id: "bluegill"
  name: "Bluegill"
  size: 25
  rarity: 0
  startHour: 9
  endHour: 16
  emoji: "ğŸ "
- id: "carp"
  name: "Carp"
  size: 60
  rarity: 0
  location: "river"
- id: "catfish"
  name: "Catfish"
  size: 60
  rarity: 0
  location: "pond"
  activeMonths: 0b000011111100
- id: "char"
  name: "Char"
  size: 50
  rarity: 2
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b001111001110
- id: "cherry_salmon"
  name: "Cherry Salmon"
  size: 35
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b001111000000
- id: "coelacanth"
  name: "Coelacanth"
  size: 150
  rarity: 2
  location: "sea"
  onlyRain: true
- id: "crucian_carp"
  name: "Crucian Carp"
  size: 20
  rarity: 0
  location: "river"
- id: "dace"
  name: "Dace"
  size: 35
  rarity: 0
  location: "river"
  startHour: 16
  endHour: 9
- id: "eel"
  name: "Eel"
  size: 100
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
  emoji: "ğŸ"
- id: "freshwater_goby"
  name: "Freshwater Goby"
  size: 15
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
- id: "giant_catfish"
  name: "Giant Catfish"
  size: 40
  rarity: 1
  location: "lake"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001110000
- id: "giant_snakehead"
  name: "Giant Snakehead"
  size: 85
  rarity: 2
  location: "pond"
  startHour: 9
  endHour: 16
- id: "goldfish"
  name: "Goldfish"
  size: 15
  rarity: 0
  location: "pond"
  emoji: "ğŸ "
- id: "guppy"
  name: "Guppy"
  size: 4
  rarity: 2
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000111111110
  emoji: "ğŸ "
- id: "herabuna"
  name: "Herabuna"
  size: 50
  rarity: 0
  location: "lake"
- id: "koi"
  name: "Koi"
  size: 60
  rarity: 1
  location: "pond"
  startHour: 16
  endHour: 9
- id: "large_bass"
  name: "Large Bass"
  size: 75
  rarity: 1
  location: "river"
- id: "loach"
  name: "Loach"
  size: 20
  rarity: 0
  location: "river"
  activeMonths: 0b001110000000
- id: "pale_chub"
  name: "Pale Chub"
  size: 15
  rarity: 1
  location: "river"
  emoji: "ğŸ "
- id: "piranha"
  name: "Piranha"
  size: 30
  rarity: 2
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000001111000
  emoji: "ğŸ "
- id: "pond_smelt"
  name: "Pond Smelt"
  size: 15
  rarity: 0
  location: "river"
  activeMonths: 0b110000000001
- id: "pop-eyed_goldfish"
  name: "Pop-Eyed Goldfish"
  size: 15
  rarity: 1
  location: "pond_smelt"
  startHour: 9
  endHour: 4
- id: "rainbow_trout"
  name: "Rainbow Trout"
  size: 60
  rarity: 0
  location: "river"
  startHour: 4
  endHour: 21
  activeMonths: 0b001111001110
- id: "salmon"
  name: "Salmon"
  size: 90
  rarity: 0
  location: "river"
  activeMonths: 0b000000001000
- id: "small_bass"
  name: "Small Bass"
  size: 30
  rarity: 0
  location: "river"
- id: "stringfish"
  name: "Stringfish"
  size: 140
  rarity: 2
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b111000000001
- id: "sweetfish"
  name: "Sweetfish"
  size: 25
  rarity: 1
  location: "river"
  activeMonths: 0b000000111000
- id: "arapaima"
  name: "Arapaima"
  size: 300
  rarity: 2
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
- id: "barred_knifejaw"
  name: "Barred Knifejaw"
  size: 60
  rarity: 1
  location: "sea"
  activeMonths: 0b001111111110
  emoji: "ğŸ "
- id: "brook_trout"
  name: "Brook Trout"
  size: 50
  rarity: 0
  location: "lake"
- id: "crawfish"
  name: "Crawfish"
  size: 12
  rarity: 0
  location: "pond"
  activeMonths: 0b000111111000
  emoji: "ğŸ¦€"
- id: "frog"
  name: "Frog"
  size: 12
  rarity: 0
  location: "pond"
  activeMonths: 0b000011110000
  emoji: "ğŸ¸"
- id: "jellyfish"
  name: "Jellyfish"
  size: 25
  rarity: 1
  location: "sea"
  activeMonths: 0b000000111000
  emoji: "ğŸª¼"
- id: "moon_jellyfish"
  name: "Moon jellyfish"
  size: 30
  rarity: 1
  location: "sea"
  activeMonths: 0b000001111000
- id: "killifish"
  name: "Killifish"
  size: 4
  rarity: 1
  location: "pond"
  activeMonths: 0b000111110000
- id: "red_snapper"
  name: "Red Snapper"
  size: 90
  rarity: 1
  location: "sea"
- id: "sea_bass"
  name: "Sea Bass"
  size: 100
  rarity: 0
  location: "sea"
- id: "blue_marlin"
  name: "Blue Marlin"
  size: 220
  rarity: 2
  location: "sea" # "pier"
  activeMonths: 0b111100111011
- id: "dab"
  name: "Dab"
  size: 50
  rarity: 1
  location: "sea"
  activeMonths: 0b111100000111
- id: "horse_mackerel"
  name: "Horse Mackerel"
  size: 40
  rarity: 0
  location: "sea"
- id: "octopus"
  name: "Octopus"
  size: 50
  rarity: 0
  location: "sea"
  emoji: "ğŸ™"
- id: "olive_flounder"
  name: "Olive Flounder"
  size: 80
  rarity: 0
  location: "sea"
- id: "puffer_fish"
  name: "Puffer fish"
  size: 35
  rarity: 1
  location: "sea"
  emoji: "ğŸ¡"
- id: "sea_horse"
  name: "Sea Horse"
  size: 8
  rarity: 0
  location: "sea"
  activeMonths: 0b000111111110
  emoji: "ğŸ´"
- id: "squid"
  name: "Squid"
  size: 35
  rarity: 0
  location: "sea"
  activeMonths: 0b111111110001
  emoji: "ğŸ¦‘"
- id: "black_bass"
  name: "Black bass"
  size: 50
  rarity: 0
  location: "river"
- id: "clown_fish"
  name: "Clown fish"
  size: 15
  rarity: 0
  location: "sea"
  activeMonths: 0b000111111000
  emoji: "ğŸ "
- id: "dorado"
  name: "Dorado"
  size: 100
  rarity: 2
  location: "river"
  activeMonths: 0b000001111000
- id: "football_fish"
  name: "Football Fish"
  size: 60
  rarity: 1
  startHour: 16
  endHour: 9
  location: "sea"
- id: "gar"
  name: "Gar"
  size: 190
  rarity: 1
  location: "pond"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
- id: "great_white_shark"
  name: "Great White Shark"
  size: 540
  rarity: 2
  location: "sea"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
  emoji: "ğŸ¦ˆ"
- id: "hammerhead_shark"
  name: "Hammerhead Shark"
  size: 250
  rarity: 2
  location: "sea"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
  emoji: "ğŸ¦ˆ"
- id: "king_salmon"
  name: "King Salmon"
  size: 140
  rarity: 1
  location: "river"
  activeMonths: 0b000000001000
- id: "ocean_sunfish"
  name: "Ocean Sunfish"
  size: 300
  rarity: 2
  location: "sea"
  startHour: 4
  endHour: 21
- id: "sea_butterfly"
  name: "Sea Butterfly"
  size: 3
  rarity: 0
  location: "sea"
  activeMonths: 0b111000000001
- id: "tuna"
  name: "Tuna"
  size: 230
  rarity: 2
  location: "sea"
  activeMonths: 0b111100000011
- id: "yellow_perch"
  name: "Yellow Perch"
  size: 35
  rarity: 0
  location: "river"
  activeMonths: 0b111000001111
  emoji: "ğŸ "
- id: "zebra_turkeyfish"
  name: "Zebra Turkeyfish"
  size: 30
  rarity: 0
  location: "sea"
  activeMonths: 0b111100000011
  emoji: "ğŸ "
- id: "butterfly_fish"
  name: "Butterfly Fish"
  size: 18
  rarity: 1
  location: "sea"
  activeMonths: 0b111100001111
  emoji: "ğŸ "
- id: "lobster"
  name: "Lobster"
  size: 50
  rarity: 2
  location: "sea"
  activeMonths: 0b100111000001
  emoji: "ğŸ¦"
- id: "mooray_eel"
  name: "Mooray Eel"
  size: 80
  rarity: 1
  location: "sea"
  activeMonths: 0b000000011100
  emoji: "ğŸ"
- id: "napoleanfish"
  name: "Napoleanfish"
  size: 180
  rarity: 2
  location: "sea"
  startHour: 4
  endHour: 21
  activeMonths: 0b000000110000
  emoji: "ğŸ "
- id: "neon_tetra"
  name: "Neon Tetra"
  size: 2
  rarity: 1
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000111111110
  emoji: "ğŸ "
- id: "pike"
  name: "Pike"
  size: 120
  rarity: 1
  location: "river"
  activeMonths: 0b000000001111
- id: "ray"
  name: "Ray"
  size: 120
  rarity: 1
  location: "sea"
  startHour: 4
  endHour: 21
  activeMonths: 0b000000011110
- id: "surgeonfish"
  name: "Surgeonfish"
  size: 31
  rarity: 1
  location: "sea"
  activeMonths: 0b000111111000
  emoji: "ğŸ "
- id: "blowfish"
  name: "Blowfish"
  size: 25
  rarity: 1
  location: "sea"
  startHour: 21
  endHour: 4
  activeMonths: 0b110000000011
  emoji: "ğŸ¡"
- id: "giant_trevally"
  name: "Giant Trevally"
  size: 180
  rarity: 2
  location: "sea"
  activeMonths: 0b000011111100
- id: "mitten_crab"
  name: "Mitten Crab"
  size: 8
  rarity: 2
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000000001110
  emoji: "ğŸ¦€"
- id: "nibble_fish"
  name: "Nibble Fish"
  size: 8
  rarity: 2
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000011111000
- id: "oarfish"
  name: "Oarfish"
  size: 580
  rarity: 2
  location: "sea"
  activeMonths: 0b111110000001
  emoji: "ğŸ "
- id: "ribbon_eel"
  name: "Ribbon Eel"
  size: 120
  rarity: 1
  location: "sea"
  activeMonths: 0b000001111100
  emoji: "ğŸ"
- id: "saddled_bichir"
  name: "Saddled Bichir"
  size: 60
  rarity: 1
  location: "river"
  startHour: 21
  endHour: 4
  activeMonths: 0b000001111000
- id: "saw_shark"
  name: "Saw Shark"
  size: 150
  rarity: 2
  location: "sea"
  startHour: 16
  endHour: 9
  activeMonths: 0b000001111000
  emoji: "ğŸ¦ˆ"
- id: "soft-shelled_turtle"
  name: "Soft-Shelled Turtle"
  size: 30
  rarity: 1
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b000000011000
  emoji: "ğŸ¢"
- id: "tadpole"
  name: "Tadpole"
  size: 4
  rarity: 0
  location: "pond"
  activeMonths: 0b001111100000
  emoji: "ğŸ¸"
- id: "whale_shark"
  name: "Whale Shark"
  size: 600
  rarity: 2
  location: "sea"
  activeMonths: 0b000001111000
  emoji: "ğŸ¦ˆ"
- id: "anchovy"
  name: "Anchovy"
  size: 15
  rarity: 1
  location: "sea"
  startHour: 4
  endHour: 21
- id: "barreleye"
  name: "Barreleye"
  size: 20
  rarity: 2
  location: "sea"
  startHour: 21
  endHour: 4
- id: "betta"
  name: "Betta"
  size: 7
  rarity: 1
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000011111100
  emoji: "ğŸ "
- id: "golden_trout"
  name: "Golden Trout"
  size: 30
  rarity: 2
  location: "river"
  startHour: 16
  endHour: 9
  activeMonths: 0b001110001110
- id: "mahi-mahi"
  name: "Mahi-Mahi"
  size: 110
  rarity: 2
  location: "sea"
  activeMonths: 0b000011111100
  emoji: "ğŸ "
- id: "rainbowfish"
  name: "Rainbowfish"
  size: 12
  rarity: 1
  location: "river"
  startHour: 9
  endHour: 16
  activeMonths: 0b000011111100
  emoji: "ğŸ "
- id: "ranchu_goldfish"
  name: "Ranchu Goldfish"
  size: 15
  rarity: 1
  location: "pond"
  startHour: 9
  endHour: 16
  emoji: "ğŸ "
- id: "snapping_turtle"
  name: "Snapping Turtle"
  size: 50
  rarity: 0
  location: "river"
  startHour: 21
  endHour: 4
  activeMonths: 0b000111111100
  emoji: "ğŸ¢"
- id: "sturgeon"
  name: "Sturgeon"
  size: 20
  rarity: 2
  location: "river"
  activeMonths: 0b111000001111
- id: "suckerfish"
  name: "Suckerfish"
  size: 110
  rarity: 2
  location: "sea"
  activeMonths: 0b000001111000
- id: "tilapia"
  name: "Tilapia"
  size: 20
  rarity: 0
  location: "river"
  activeMonths: 0b000001111100

# Sea creatures (https://nookipedia.com/wiki/Sea_creature)
#* Duplicate catches are not included
- id: "abalone"
  name: "Abalone"
  size: 10
  rarity: 0
  location: "sea"
  activeMonths: 0b100001111111
  emoji: "ğŸš"
- id: "acorn_barnacle"
  name: "Acorn Barnacle"
  size: 3
  rarity: 0
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸš"
- id: "chambered_nautilus"
  name: "Chambered nautilus"
  size: 35
  rarity: 0
  location: "sea"
  activeMonths: 0b001111001110
  emoji: "ğŸ¦"
- id: "clam"
  name: "Clam"
  size: 4
  rarity: 0
  location: "sea"
  activeMonths: 0b111100001111
  emoji: "ğŸš"
- id: "ear_shell"
  name: "Ear Shell"
  size: 7
  rarity: 0
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸš"
- id: "flatworm"
  name: "Flatworm"
  size: 4
  rarity: 0
  location: "sea"
  activeMonths: 0b000000011000
  emoji: "ğŸª±"
- id: "giant_isopod"
  name: "Giant Isopod"
  size: 30
  rarity: 0
  location: "sea"
  activeMonths: 0b000001111100
  emoji: "ğŸª±"
- id: "horsehair_crab"
  name: "Horsehair Crab"
  size: 24
  rarity: 2
  location: "sea"
  activeMonths: 0b111100000011
  emoji: "ğŸ¦€"
- id: "horseshoe_crab"
  name: "Horseshoe Crab"
  size: 40
  rarity: 3
  location: "sea"
  activeMonths: 0b000000111000
  emoji: "ğŸ§²"
- id: "mantis_shrimp"
  name: "Mantis Shrimp"
  size: 12
  rarity: 2
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸ¦"
- id: "oyster"
  name: "Oyster"
  size: 8
  rarity: 0
  location: "sea"
  activeMonths: 0b110000001111
  emoji: "ğŸ¦ª"
- id: "pearl_oyster"
  name: "Pearl Oyster"
  size: 10
  rarity: 3
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸ¦ª"
- id: "red_king_crab"
  name: "Red King Crab"
  size: 50
  rarity: 4
  location: "sea"
  activeMonths: 0b111000000011
  emoji: "ğŸ¦€"
- id: "scallop"
  name: "Scallop"
  size: 14
  rarity: 2
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸ¦ª"
- id: "sea_anemone"
  name: "Sea anemone"
  size: 20
  rarity: 1
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸª¸"
- id: "sea_cucumber"
  name: "Sea cucumber"
  size: 60
  rarity: 1
  location: "sea"
  activeMonths: 0b111100000011
  emoji: "ğŸ¥’"
- id: "sea_grapes"
  name: "Sea grapes"
  size: 20
  rarity: 1
  location: "sea"
  activeMonths: 0b000001111000
  emoji: "ğŸ‡"
- id: "sea_slug"
  name: "Sea slug"
  size: 4
  rarity: 1
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸŒ"
- id: "sea_star"
  name: "Sea star"
  size: 25
  rarity: 0
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "â­"
- id: "sea_urchin"
  name: "Sea urchin"
  size: 12
  rarity: 1
  location: "sea"
  activeMonths: 0b000001110000
  emoji: "ğŸ¡"
- id: "seaweed"
  name: "Seaweed"
  size: 80
  rarity: 0
  location: "sea"
  activeMonths: 0b111111100111
  emoji: "ğŸŒ±"
- id: "snow_crab"
  name: "Snow crab"
  size: 30
  rarity: 2
  location: "sea"
  activeMonths: 0b111100000011
  emoji: "ğŸ¦€"
- id: "spider_crab"
  name: "Spider crab"
  size: 120
  rarity: 3
  location: "sea"
  activeMonths: 0b001100000000
  emoji: "ğŸ¦€"
- id: "spiny_lobster"
  name: "Spiny lobster"
  size: 30
  rarity: 3
  location: "sea"
  activeMonths: 0b000000000111
  emoji: "ğŸ¦"
- id: "spotted_garden_eel"
  name: "Spotted garden eel"
  size: 17
  rarity: 2
  location: "sea"
  activeMonths: 0b000011111100
  emoji: "ğŸ"
- id: "sweet_shrimp"
  name: "Sweet shrimp"
  size: 12
  rarity: 1
  location: "sea"
  activeMonths: 0b110000001111
  emoji: "ğŸ¦"
- id: "tiger_prawn"
  name: "Tiger prawn"
  size: 20
  rarity: 2
  location: "sea"
  activeMonths: 0b000001111000
  emoji: "ğŸ¦"
- id: "turban_shell"
  name: "Turban shell"
  size: 12
  rarity: 2
  location: "sea"
  activeMonths: 0b001110001111
  emoji: "ğŸš"
- id: "dungeness_crab"
  name: "Dungeness crab"
  size: 10
  rarity: 1
  location: "sea"
  activeMonths: 0b111110000011
  emoji: "ğŸ¦€"
- id: "firefly_squid"
  name: "Firefly squid"
  size: 5
  rarity: 3
  location: "sea"
  activeMonths: 0b001111000000
  emoji: "ğŸ¦‘"
- id: "gazami_crab"
  name: "Gazami crab"
  size: 15
  rarity: 3
  location: "sea"
  activeMonths: 0b000001111110
  emoji: "ğŸ¦€"
- id: "gigas_giant_clam"
  name: "Gigas giant clam"
  size: 115
  rarity: 4
  location: "sea"
  activeMonths: 0b000011111000
  emoji: "ğŸ¦ª"
- id: "mussel"
  name: "Mussel"
  size: 5
  rarity: 1
  location: "sea"
  activeMonths: 0b000001111111
  emoji: "ğŸ¦ª"
- id: "sea_pig"
  name: "Sea pig"
  size: 3
  rarity: 1
  location: "sea"
  activeMonths: 0b110000000011
  emoji: "ğŸ–"
- id: "sea_pineapple"
  name: "Sea pineapple"
  size: 10
  rarity: 1
  location: "sea"
  activeMonths: 0b000111110000
  emoji: "ğŸ"
- id: "slate_pencil_urchin"
  name: "Slate pencil urchin"
  size: 20
  rarity: 2
  location: "sea"
  activeMonths: 0b000011111000
  emoji: "ğŸ¡"
- id: "umbrella_octopus"
  name: "Umbrella octopus"
  size: 30
  rarity: 3
  location: "sea"
  activeMonths: 0b001110001110
  emoji: "ğŸ™"
- id: "vampire_squid"
  name: "Vampire squid"
  size: 20
  rarity: 3
  location: "sea"
  activeMonths: 0b000011110000
  emoji: "ğŸ¦‘"
- id: "venus_flower_basket"
  name: "Venus' flower basket"
  size: 25
  rarity: 4
  location: "sea"
  activeMonths: 0b110000000111
  emoji: "ğŸ§º"
- id: "whelk"
  name: "Whelk"
  size: 3
  rarity: 0
  location: "sea"
  activeMonths: 0b111111111111
  emoji: "ğŸŒ"
