- uri: wss://mppclone.com:8443
  channel:
      id: "âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§"
      allowColorChanging: true
- uri: wss://mppclone.com:8443
  channel:
      id: "test/fishing"
      allowColorChanging: true
